<?xml version="1.0" encoding="UTF-8"?>
<GROCERY xsi:schemalocation="kunal1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<!DOCTYPE GROCERY [
<!ELEMENT GROCERY (to,from,type,price,subject,messsage)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT message (#PCDATA)>
]>
<GROCERY>
    <to>Kunal Varadkar</to>
    <from>DMART SERVICES</from>
    <type>Groceries</type>
    <price>500RS</price>
    <subject>THANK YOU FOR VISITING</subject>
    <message>REGARDS DMART</message>   
</GROCERY>
